/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.2.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 2019年10月2日
 ***********************************************************************************************/

#include "sensors_information_interface.h"

#define MAX_MASSAGE_SIZE 256

//
// Application state associated with this interface.
// It contains the DIGITALTWIN_INTERFACE_CLIENT_HANDLE used for responses in callbacks along with properties set
// and representations of the property update and command callbacks invoked on given interface
//
typedef struct SENSORS_INFORMATION_INTERFACE_STATE_TAG
{
    DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceClientHandle;

} SENSORS_INFORMATION_INTERFACE_STATE;

static SENSORS_INFORMATION_INTERFACE_STATE appState;

// Sensors_InformationInterface_TelemetryCallback is invoked when a DigitalTwin telemetry message is either successfully delivered to the service or else fails.
static void Sensors_InformationInterface_TelemetryCallback(DIGITALTWIN_CLIENT_RESULT digitalTwinTelemetryStatus, void* userContextCallback)
{
    if (digitalTwinTelemetryStatus == DIGITALTWIN_CLIENT_OK)
    {
        SendTelemetry_Succeeded_Callback("Sensors_Information", (const char*)userContextCallback);
        LogInfo("SENSORS_INFORMATION_INTERFACE: DigitalTwin successfully delivered telemetry message for <%s>", (const char*)userContextCallback);
    }
    else
    {
        SendTelemetry_Error_Callback("Sensors_Information", (const char*)userContextCallback);
        LogError("SENSORS_INFORMATION_INTERFACE: DigitalTwin failed to deliver telemetry message for <%s>, error=<%s> ", (const char*)userContextCallback, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, digitalTwinTelemetryStatus));
    }
}

// SendTelemetry is a helper function which is periodically invoked by the caller to send telemetry
DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_SendTelemetry_Internal(DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceHandle, const char* telemetryName, const char* telemetryData)
{
    DIGITALTWIN_CLIENT_RESULT result;

    result = DigitalTwin_InterfaceClient_SendTelemetryAsync(interfaceHandle, telemetryName, telemetryData,
        Sensors_InformationInterface_TelemetryCallback, (void*)telemetryName);

    if (result != DIGITALTWIN_CLIENT_OK)
    {
        LogError("SENSORS_INFORMATION_INTERFACE:: DigitalTwin_InterfaceClient_SendTelemetryAsync failed for sending %s", telemetryName);
    }
    else
    {
        LogInfo("SENSORS_INFORMATION_INTERFACE:: DigitalTwin_InterfaceClient_SendTelemetryAsync successfully sent %s", telemetryName);
    }

    DigitalTwinClientHelper_Check();
    return result;
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendAll()
{
    DIGITALTWIN_CLIENT_RESULT result;

    // NOTE: Future versions of SDK will support ability to send multiple telemetries in a single
    // send.  For now, one at a time is sufficient albeit less efficient.
    if (((result = Sensors_InformationInterface_Telemetry_SendVvcore()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendVvcore2()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendV25v()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendV33v()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendV5v()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendV12v()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendV5vstandby()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendV3vstandby()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendVcmosbattery()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendV5nv()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendV12nv()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendVvtt()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendV24v()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendTcpu()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendTchipset()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendTsystem()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendTcpu2()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendFcpu()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = Sensors_InformationInterface_Telemetry_SendFsystem()) != DIGITALTWIN_CLIENT_OK) || 
        ((result = Sensors_InformationInterface_Telemetry_SendFcpu2()) != DIGITALTWIN_CLIENT_OK) )

    {
        LogError("SENSORS_INFORMATION_INTERFACE: failed to send telemetries");
    }
    else
    {
        LogInfo("SENSORS_INFORMATION_INTERFACE: Queuing of all telemetries to be sent has succeeded");
    }

    return result;
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendVvcore()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeVvcoreTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_VvcoreTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message vvcore failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendVvcore2()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeVvcore2Telemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_Vvcore2Telemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message vvcore2 failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendV25v()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeV25vTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_V25vTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message v25v failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendV33v()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeV33vTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_V33vTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message v33v failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendV5v()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeV5vTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_V5vTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message v5v failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendV12v()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeV12vTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_V12vTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message v12v failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendV5vstandby()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeV5vstandbyTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_V5vstandbyTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message v5vstandby failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendV3vstandby()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeV3vstandbyTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_V3vstandbyTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message v3vstandby failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendVcmosbattery()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeVcmosbatteryTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_VcmosbatteryTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message vcmosbattery failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendV5nv()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeV5nvTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_V5nvTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message v5nv failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendV12nv()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeV12nvTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_V12nvTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message v12nv failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendVvtt()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeVvttTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_VvttTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message vvtt failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendV24v()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeV24vTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_V24vTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message v24v failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendTcpu()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeTcpuTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_TcpuTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message tcpu failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendTchipset()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeTchipsetTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_TchipsetTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message tchipset failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendTsystem()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeTsystemTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_TsystemTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message tsystem failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendTcpu2()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeTcpu2Telemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_Tcpu2Telemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message tcpu2 failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendFcpu()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeFcpuTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_FcpuTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message fcpu failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendFsystem()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeFsystemTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_FsystemTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message fsystem failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT Sensors_InformationInterface_Telemetry_SendFcpu2()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensors_Information_SerializeFcpu2Telemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return Sensors_InformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, Sensors_InformationInterface_Fcpu2Telemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: serialize telemetry message fcpu2 failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

// Sensors_InformationInterface_InterfaceRegisteredCallback is invoked when this interface
// is successfully or unsuccessfully registered with the service, and also when the interface is deleted.
static void Sensors_InformationInterface_InterfaceRegisteredCallback(DIGITALTWIN_CLIENT_RESULT dtInterfaceStatus, void* userInterfaceContext)
{
    LogInfo("Sensors_InformationInterface_InterfaceRegisteredCallback with status=<%s>, userContext=<%p>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, dtInterfaceStatus), userInterfaceContext);
    if (dtInterfaceStatus == DIGITALTWIN_CLIENT_OK)
    {
        // Once the interface is registered, send our reported properties to the service.  
        // It *IS* safe to invoke most DigitalTwin API calls from a callback thread like this, though it 
        // is NOT safe to create/destroy/register interfaces now.
        LogInfo("SENSORS_INFORMATION_INTERFACE: Interface successfully registered.");
    }
    else if (dtInterfaceStatus == DIGITALTWIN_CLIENT_ERROR_INTERFACE_UNREGISTERING)
    {
        // Once an interface is marked as unregistered, it cannot be used for any DigitalTwin SDK calls.
        LogInfo("SENSORS_INFORMATION_INTERFACE: Interface received unregistering callback.");
    }
    else
    {
        LogError("SENSORS_INFORMATION_INTERFACE: Interface received failed, status=<%s>.", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, dtInterfaceStatus));
    }
}

//
// Create DigitalTwin interface client handle
//
DIGITALTWIN_INTERFACE_CLIENT_HANDLE Sensors_InformationInterface_Create()
{
    DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceHandle;
    DIGITALTWIN_CLIENT_RESULT result;

    memset(&appState, 0, sizeof(SENSORS_INFORMATION_INTERFACE_STATE));

    if ((result = DigitalTwin_InterfaceClient_Create(Sensors_InformationInterfaceId,  Sensors_InformationInterfaceInstanceName, Sensors_InformationInterface_InterfaceRegisteredCallback, (void*)&appState, &interfaceHandle)) != DIGITALTWIN_CLIENT_OK)
    {
        LogError("SENSORS_INFORMATION_INTERFACE: Unable to allocate interface client handle for interfaceId=<%s>, interfaceInstanceName=<%s>, error=<%s>", Sensors_InformationInterfaceId, Sensors_InformationInterfaceInstanceName, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
        interfaceHandle = NULL;
    }

    else
    {
        LogInfo("SENSORS_INFORMATION_INTERFACE: Created DIGITALTWIN_INTERFACE_CLIENT_HANDLE successfully for interfaceId=<%s>, interfaceInstanceName=<%s>, handle=<%p>", Sensors_InformationInterfaceId, Sensors_InformationInterfaceInstanceName, interfaceHandle);
        appState.interfaceClientHandle = interfaceHandle;
    }

    return interfaceHandle;
}

void Sensors_InformationInterface_Close(DIGITALTWIN_INTERFACE_CLIENT_HANDLE digitalTwinInterfaceClientHandle)
{
    // On shutdown, in general the first call made should be to DigitalTwin_InterfaceClient_Destroy.
    // This will block if there are any active callbacks in this interface, and then
    // mark the underlying handle such that no future callbacks shall come to it.
    DigitalTwin_InterfaceClient_Destroy(digitalTwinInterfaceClientHandle);

    // After DigitalTwin_InterfaceClient_Destroy returns, it is safe to assume
    // no more callbacks shall arrive for this interface and it is OK to free
    // resources callbacks otherwise may have needed.

}
