/*******************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.2.
 *
 * You need to add your implementation here to:
 *    - get telemetry data from device/sensor
 *    - set read-only property data
 *    - handle read-write property callback
 *    - process device command
 *
 * Generated Date: 2019年10月2日
 *******************************************************************************************/

#include "SUSI_HWM.h"
#include "utilities/digitaltwin_serializer.h"
#include "utilities/device_detailed_information_interface.h"
#include "utilities/sensors_information_interface.h"
#include "utilities/deviceinfo_interface.h"
#include "Susi4.h"

#define Payload_Buffer_Size 256

char* gLastConnectedAt = NULL;

void SendTelemetry_Succeeded_Callback(const char* interfaceName, const char* telemetryName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on success.

    LogInfo("DigitalTwin successfully delivered telemetry message for %s::%s", interfaceName, telemetryName);
}

void SendTelemetry_Error_Callback(const char* interfaceName, const char* telemetryName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on failure.

    LogInfo("DigitalTwin failed to deliver telemetry message for %s::%s", interfaceName, telemetryName);
}

void ReportProperty_Succeeded_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback reporting property on success.

    LogInfo("DigitalTwin successfully report writable property for %s::%s", interfaceName, propertyName);
}

void ReportProperty_Error_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback of reporting property on failure.

    LogInfo("DigitalTwin failed to report writable property for %s::%s", interfaceName, propertyName);
}

char* Device_Detailed_Information_Property_GetBiosVersion()
{
    // TODO: provide implementation here

    SusiStatus_t biosVersion;
    uint32_t bufLen;
    char* buf = malloc(1024 * sizeof(char));
    biosVersion = SusiBoardGetStringA(SUSI_ID_BOARD_BIOS_REVISION_STR, buf, &bufLen);
    if (biosVersion == SUSI_STATUS_SUCCESS)
    {
        LogInfo("BiosVersion: %s", buf);
    }
    else
    {
        LogInfo("BiosVersion error code: %lu", biosVersion);
        sprintf(buf, "NULL");
        buf[strlen(buf)] = '\0';
    }
    return buf;
}

char* Device_Detailed_Information_Property_GetECFirmware()
{
    // TODO: provide implementation here
    SusiStatus_t ecFW;
    uint32_t bufLen;
    char* buf = malloc(1024 * sizeof(char));
    ecFW = SusiBoardGetStringA(SUSI_ID_BOARD_EC_FW_STR, buf, &bufLen);
    if (ecFW == SUSI_STATUS_SUCCESS)
    {
        LogInfo("ECFirmware: %s", buf);
    }
    else
    {
        LogInfo("ECFirmware error code: %lu", ecFW);
        sprintf(buf, "NULL");
        buf[strlen(buf)] = '\0';
    }
    return buf;
}

char* Device_Detailed_Information_Property_GetDriverVersion()
{
    SusiStatus_t driverVersion;
    uint32_t buf;
    char* buffer = malloc(1024 * sizeof(char));

    driverVersion = SusiBoardGetValue(SUSI_ID_BOARD_DRIVER_VERSION_VAL, &buf);
    if (driverVersion == SUSI_STATUS_SUCCESS)
    {
        LogInfo("driverVersion: %u.%u.%u", (buf >> 24), ((buf >> 16) & 0xFF), (buf & 0xFFFF));
        sprintf(buffer, "%u.%u.%u", (buf >> 24), ((buf >> 16) & 0xFF), (buf & 0xFFFF));
        buffer[strlen(buffer)] = '\0';
    }
    else
    {
        LogInfo("driverVersion error code: %lu", driverVersion);
        sprintf(buffer, "NULL");
        buffer[strlen(buffer)] = '\0';
    }
    return buffer;
}

char* Device_Detailed_Information_Property_GetLibraryVersion()
{
    SusiStatus_t libVersion;
    uint32_t buf;
    char* buffer = malloc(1024 * sizeof(char));

    libVersion = SusiBoardGetValue(SUSI_ID_BOARD_LIB_VERSION_VAL, &buf);
    if (libVersion == SUSI_STATUS_SUCCESS)
    {
        LogInfo("libVersion: %u.%u.%u", (buf >> 24), ((buf >> 16) & 0xFF), (buf & 0xFFFF));
        sprintf(buffer, "%u.%u.%u", (buf >> 24), ((buf >> 16) & 0xFF), (buf & 0xFFFF));
        buffer[strlen(buffer)] = '\0';
    }
    else
    {
        LogInfo("libVersion error code: %lu", libVersion);
        sprintf(buffer, "NULL");
        buffer[strlen(buffer)] = '\0';
    }
    return buffer;
}


char* Device_Detailed_Information_Property_GetFirmwareVersion()
{
    SusiStatus_t fwVersion;
    uint32_t buf;
    char* buffer = malloc(1024 * sizeof(char));

    fwVersion = SusiBoardGetValue(SUSI_ID_BOARD_FIRMWARE_VERSION_VAL, &buf);
    if (fwVersion == SUSI_STATUS_SUCCESS)
    {
        LogInfo("fwVersion: %u.%u.%u", (buf >> 24), ((buf >> 16) & 0xFF), (buf & 0xFFFF));
        sprintf(buffer, "%u.%u.%u", (buf >> 24), ((buf >> 16) & 0xFF), (buf & 0xFFFF));
        buffer[strlen(buffer)] = '\0';
    }
    else
    {
        LogInfo("fwVersion error code: %lu", fwVersion);
        sprintf(buffer, "NULL");
        buffer[strlen(buffer)] = '\0';
    }
    return buffer;
}

char* Device_Detailed_Information_Property_GetLastConnectedAt()
{
    if (gLastConnectedAt == NULL) {
        time_t rawtime;
        struct tm* info;
        char buffer[80];
        time(&rawtime);
        info = localtime(&rawtime);
        strftime(buffer, 80, "%Y-%m-%dT%H:%M:%S", info);
        gLastConnectedAt = _strdup(buffer);
    }
    return gLastConnectedAt;
    // TODO: provide implementation here
}

double Sensors_Information_Telemetry_ReadVvcore()
{
    SusiStatus_t vvcore;
    uint32_t buf;

    vvcore = SusiBoardGetValue(SUSI_ID_HWM_VOLTAGE_VCORE, &buf);
    if (vvcore == SUSI_STATUS_SUCCESS)
    {
        LogInfo("vvore: %lu mV", buf);
    }
    else
    {
        LogInfo("vvcore error code: %lu", vvcore);
    }
    return (buf * 0.001);
}

double Sensors_Information_Telemetry_ReadVvcore2()
{
    SusiStatus_t vvcore2;
    uint32_t buf;

    vvcore2 = SusiBoardGetValue(SUSI_ID_HWM_VOLTAGE_VCORE2, &buf);
    if (vvcore2 == SUSI_STATUS_SUCCESS)
    {
        LogInfo("vvore2: %lu mV", buf);
    }
    else
    {
        LogInfo("vvcore2 error code: %lu", vvcore2);
    }
    return (buf * 0.001);
}

double Sensors_Information_Telemetry_ReadV25v()
{
    SusiStatus_t v25v;
    uint32_t buf;

    v25v = SusiBoardGetValue(SUSI_ID_HWM_VOLTAGE_2V5, &buf);
    if (v25v == SUSI_STATUS_SUCCESS)
    {
        LogInfo("v25v: %lu mV", buf);
    }
    else
    {
        LogInfo("v25v error code: %lu", v25v);
    }
    return (buf * 0.001);
}

double Sensors_Information_Telemetry_ReadV33v()
{
    SusiStatus_t v33v;
    uint32_t buf;

    v33v = SusiBoardGetValue(SUSI_ID_HWM_VOLTAGE_3V3, &buf);
    if (v33v == SUSI_STATUS_SUCCESS)
    {
        LogInfo("v33v: %lu mV", buf);
    }
    else
    {
        LogInfo("v33v error code: %lu", v33v);
    }
    return (buf * 0.001);
}

double Sensors_Information_Telemetry_ReadV5v()
{
    SusiStatus_t v5v;
    uint32_t buf;

    v5v = SusiBoardGetValue(SUSI_ID_HWM_VOLTAGE_5V, &buf);
    if (v5v == SUSI_STATUS_SUCCESS)
    {
        LogInfo("v5v: %lu mV", buf);
    }
    else
    {
        LogInfo("v5v error code: %lu", v5v);
    }
    return (buf * 0.001);
}

double Sensors_Information_Telemetry_ReadV12v()
{
    SusiStatus_t v12v;
    uint32_t buf;

    v12v = SusiBoardGetValue(SUSI_ID_HWM_VOLTAGE_12V, &buf);
    if (v12v == SUSI_STATUS_SUCCESS)
    {
        LogInfo("v12v: %lu mV", buf);
    }
    else
    {
        LogInfo("v12v error code: %lu", v12v);
    }
    return (buf * 0.001);
}

double Sensors_Information_Telemetry_ReadV5vstandby()
{
    SusiStatus_t standby5v;
    uint32_t buf;

    standby5v = SusiBoardGetValue(SUSI_ID_HWM_VOLTAGE_5VSB, &buf);
    if (standby5v == SUSI_STATUS_SUCCESS)
    {
        LogInfo("standby5v: %lu mV", buf);
    }
    else
    {
        LogInfo("standby5v error code: %lu", standby5v);
    }
    return (buf * 0.001);
}

double Sensors_Information_Telemetry_ReadV3vstandby()
{
    SusiStatus_t standby3v;
    uint32_t buf;

    standby3v = SusiBoardGetValue(SUSI_ID_HWM_VOLTAGE_3VSB, &buf);
    if (standby3v == SUSI_STATUS_SUCCESS)
    {
        LogInfo("standby3v: %lu mV", buf);
    }
    else
    {
        LogInfo("standby3v error code: %lu", standby3v);
    }
    return (buf * 0.001);
}

double Sensors_Information_Telemetry_ReadVcmosbattery()
{
    SusiStatus_t vcmosbattery;
    uint32_t buf;

    vcmosbattery = SusiBoardGetValue(SUSI_ID_HWM_VOLTAGE_VBAT, &buf);
    if (vcmosbattery == SUSI_STATUS_SUCCESS)
    {
        LogInfo("vcmosbattery: %lu mV", buf);
    }
    else
    {
        LogInfo("vcmosbattery error code: %lu", vcmosbattery);
    }
    return (buf * 0.001);
}

double Sensors_Information_Telemetry_ReadV5nv()
{
    SusiStatus_t v5nv;
    uint32_t buf;

    v5nv = SusiBoardGetValue(SUSI_ID_HWM_VOLTAGE_5NV, &buf);
    if (v5nv == SUSI_STATUS_SUCCESS)
    {
        LogInfo("v5nv: %lu mV", buf);
    }
    else
    {
        LogInfo("v5nv error code: %lu", v5nv);
    }
    return (buf * 0.001);
}

double Sensors_Information_Telemetry_ReadV12nv()
{
    SusiStatus_t v12nv;
    uint32_t buf;

    v12nv = SusiBoardGetValue(SUSI_ID_HWM_VOLTAGE_12NV, &buf);
    if (v12nv == SUSI_STATUS_SUCCESS)
    {
        LogInfo("v12nv: %lu mV", buf);
    }
    else
    {
        LogInfo("v12nv error code: %lu", v12nv);
    }
    return (buf * 0.001);
}

double Sensors_Information_Telemetry_ReadVvtt()
{
    SusiStatus_t vvtt;
    uint32_t buf;

    vvtt = SusiBoardGetValue(SUSI_ID_HWM_VOLTAGE_VTT, &buf);
    if (vvtt == SUSI_STATUS_SUCCESS)
    {
        LogInfo("vvtt: %lu mV", buf);
    }
    else
    {
        LogInfo("vvtt error code: %lu", vvtt);
    }
    return (buf * 0.001);
}

double Sensors_Information_Telemetry_ReadV24v()
{
    SusiStatus_t v24v;
    uint32_t buf;

    v24v = SusiBoardGetValue(SUSI_ID_HWM_VOLTAGE_24V, &buf);
    if (v24v == SUSI_STATUS_SUCCESS)
    {
        LogInfo("v24v: %lu mV", buf);
    }
    else
    {
        LogInfo("v24v error code: %lu", v24v);
    }
    return (buf * 0.001);
}

double Sensors_Information_Telemetry_ReadTcpu()
{
    SusiStatus_t tcpu;
    uint32_t buf;

    tcpu = SusiBoardGetValue(SUSI_ID_HWM_TEMP_CPU, &buf);
    if (tcpu == SUSI_STATUS_SUCCESS)
    {
        LogInfo("tcpu: %lu 0.1K", buf);
    }
    else
    {
        LogInfo("tcpu error code: %lu", tcpu);
    }
    return (0.1 * buf - 273.15);
}

double Sensors_Information_Telemetry_ReadTchipset()
{
    SusiStatus_t tchipset;
    uint32_t buf;

    tchipset = SusiBoardGetValue(SUSI_ID_HWM_TEMP_CHIPSET, &buf);
    if (tchipset == SUSI_STATUS_SUCCESS)
    {
        LogInfo("tchipset: %lu 0.1K", buf);
    }
    else
    {
        LogInfo("tchipset error code: %lu", tchipset);
    }
    return (0.1 * buf - 273.15);
}

double Sensors_Information_Telemetry_ReadTsystem()
{
    SusiStatus_t tsystem;
    uint32_t buf;

    tsystem = SusiBoardGetValue(SUSI_ID_HWM_TEMP_SYSTEM, &buf);
    if (tsystem == SUSI_STATUS_SUCCESS)
    {
        LogInfo("tsystem: %lu 0.1K", buf);
    }
    else
    {
        LogInfo("tsystem error code: %lu", tsystem);
    }
    return (0.1 * buf - 273.15);
}

double Sensors_Information_Telemetry_ReadTcpu2()
{
    SusiStatus_t tcpu2;
    uint32_t buf;

    tcpu2 = SusiBoardGetValue(SUSI_ID_HWM_TEMP_CPU2, &buf);
    if (tcpu2 == SUSI_STATUS_SUCCESS)
    {
        LogInfo("tcpu2: %lu 0.1K", buf);
    }
    else
    {
        LogInfo("tcpu2 error code: %lu", tcpu2);
    }
    return (0.1 * buf - 273.15);
}

double Sensors_Information_Telemetry_ReadFcpu()
{
    SusiStatus_t fcpu;
    uint32_t buf;

    fcpu = SusiBoardGetValue(SUSI_ID_HWM_FAN_CPU, &buf);
    if (fcpu == SUSI_STATUS_SUCCESS)
    {
        LogInfo("fcpu: %lu RPM", buf);
    }
    else
    {
        LogInfo("fcpu error code: %lu", fcpu);
    }
    return buf;
}

double Sensors_Information_Telemetry_ReadFsystem()
{
    SusiStatus_t fsystem;
    uint32_t buf;

    fsystem = SusiBoardGetValue(SUSI_ID_HWM_FAN_SYSTEM, &buf);
    if (fsystem == SUSI_STATUS_SUCCESS)
    {
        LogInfo("fsystem: %lu RPM", buf);
    }
    else
    {
        LogInfo("fsystem error code: %lu", fsystem);
    }
    return buf;
}

double Sensors_Information_Telemetry_ReadFcpu2()
{
    SusiStatus_t fcpu2;
    uint32_t buf;

    fcpu2 = SusiBoardGetValue(SUSI_ID_HWM_FAN_CPU2, &buf);
    if (fcpu2 == SUSI_STATUS_SUCCESS)
    {
        LogInfo("fcpu2: %lu RPM", buf);
    }
    else
    {
        LogInfo("fcpu2 error code: %lu", fcpu2);
    }
    return buf;
}

char* DeviceInfo_Property_GetManufacturer()
{
    // TODO: provide implementation here
    
    SusiStatus_t status;
    uint32_t bufLen;
    char* buf = malloc(1024 * sizeof(char));
    status = SusiBoardGetStringA(SUSI_ID_BOARD_MANUFACTURER_STR, buf, &bufLen);
    if (status == SUSI_STATUS_SUCCESS)
    {
        LogInfo("manufacturer: %s", buf);
    }
    else
    {
        LogInfo("manufacturer error code: %lu", status);
    }
    return buf;
}

char* DeviceInfo_Property_GetModel()
{
    // TODO: provide implementation here
    
    SusiStatus_t status;
    uint32_t bufLen;
    char* buf = malloc(1024 * sizeof(char));
    status = SusiBoardGetStringA(SUSI_ID_BOARD_NAME_STR, buf, &bufLen);
    if (status == SUSI_STATUS_SUCCESS)
    {
        LogInfo("ModelName: %s", buf);
    }
    else
    {
        LogInfo("ModelName error code: %lu", status);
    }
    return buf;
}

char* DeviceInfo_Property_GetSwVersion()
{
    // TODO: provide implementation here
    return "v1.0.0";
}

char* DeviceInfo_Property_GetOsName()
{
    // TODO: provide implementation here
    return "Windows 10 Enterprise LTSC";
}

char* DeviceInfo_Property_GetProcessorArchitecture()
{
    // TODO: provide implementation here
    return "Atom E3900/Celeron N3350/Pentium N4200 ";
}

char* DeviceInfo_Property_GetProcessorManufacturer()
{
    // TODO: provide implementation here
    return "Intel";
}

long DeviceInfo_Property_GetTotalStorage()
{
    // TODO: provide implementation here
    return 33554432;
}

long DeviceInfo_Property_GetTotalMemory()
{
    // TODO: provide implementation here
    return 8388608;
}